[package]
name = "attacks"
version = "0.1.0"
edition = "2024"

[features]
default = []
codegen = ["rand"]

[dependencies]
aether-core = { workspace = true }
rand = { workspace = true, optional = true }

[lints]
workspace = true

[[bin]]
name = "gen_magics"
required-features = ["codegen"]
path = "src/bin/gen_magics.rs"
